### ISSUE TITLE
OAS type inconsistency

### ISSUE THREAD

**Issue by JohnCarrollSplit** [FusionAuth/fusionauth-openapi#1]
I have noticed a type inconsistency between the OAS docs for the API and the actual usage and example usage of the API.

This is based on the current API spec at [https://github.com/FusionAuth/fusionauth-openapi/blob/master/openapi.yaml](https://www.google.com/url?q=https://github.com/FusionAuth/fusionauth-openapi/blob/master/openapi.yaml&source=gmail-imap&ust=1658508079000000&usg=AOvVaw2w7RxLMd5zH0m4AJ-5SK06)

This same issue appears across multiple components but for a concrete example in the User component expiry field:

expiry:
"$ref": "#/components/schemas/ZonedDateTime"

The field reference is for a type of ZonedDateTime but the actual type is a numeric (long)

In the example response displayed on this page - [https://fusionauth.io/docs/v1/tech/apis/users#reactivate-a-user](https://www.google.com/url?q=https://fusionauth.io/docs/v1/tech/apis/users%23reactivate-a-user&source=gmail-imap&ust=1658508079000000&usg=AOvVaw2V6_egJxWkeP7tVP4v5qIl) - you can see that "expiry" is in fact numeric with no timezone representation and not a ZonedDateTime

**Comment by robotdan** [comment]
When using a typed domain such as Java - we do use a `ZonedDateTime` for all instants which are serialized and de-serialized as an 8 byte integer (long). 

I am not an OpenAPI expert, so perhaps I need to do some more research, but since that is a component ref and we do define that component as a 64 bit integer, it seems correct to me. 

```yaml
ZonedDateTime:
  description: A date-time with a time-zone in the ISO-8601 calendar system, such
        as 2007-12-03T10:15:30+01:00 Europe/Paris.
  example: '2007-12-03'
  type: integer
  format: int64
```

Are you suggesting it would be better if we replaced this 

```yaml
insertInstant:
  $ref": "#/components/schemas/ZonedDateTime"
```

with this?

```yaml
insertInstant:
  type: integer
  format: int64
```

I think there is some benefit to describing these fields as a zoned date / time because it provides some additional context to the type of 8 byte integer we are expecting.
