### ISSUE TITLE
WebAuthn `public-key` enumeration incorrectly stated as `publicKey`

### ISSUE THREAD

**Issue by kdubb** [FusionAuth/fusionauth-openapi#33]
The enumeration value seems to be incorrectly stated in camel-case instead of kebab-case.

#/Components/Schemas/PublicKeyCredentialType
```
PublicKeyCredentialType:
  description: Defines valid credential types. This is an extension point in the
    WebAuthn spec. The only defined value at this time is "public-key"
  type: string
  enum:
  - publicKey
```
