### ISSUE TITLE
Discrepancy in OpenAPI specification for Errors on /api/user/change-password

### ISSUE THREAD

**Issue by brian-knoll-micronetonline** [FusionAuth/fusionauth-openapi#40]
I am using 1.56 and when I do a change password (/api/user/change-password) with the wrong data i get some error json that matches up with [API Errors](https://fusionauth.io/docs/apis/errors)
```
{
    "fieldErrors": {
        "currentPassword": [
            {
                "code": "[invalid]currentPassword",
                "message": "The [currentPassword] property is invalid. The value does not match the user's current password."
            }
        ]
    },
    "generalErrors": [
    ]
}
```
But this does not match up with the yaml in [this area](https://github.com/FusionAuth/fusionauth-openapi/blob/3e2cb877ea2a5c3b52f071464320a82e7f6a3ee8/openapi.yaml#L2004-L2007)
```
        fieldErrors:
          type: array
          items:
            "$ref": "#/components/schemas/Error"
```
I believe the correct yaml for that area would be
```
        fieldErrors:
          type: object
          additionalProperties:
            type: array
            items:
              "$ref": "#/components/schemas/Error"
```
